language: python
python:
  - 2.7
  - 3.4
  - 3.6
before_install:
 - pip install --upgrade pip setuptools wheel
 - pip install --only-binary=all scipy cython numpy pandas matplotlib coveralls
install:
  - python setup.py install
script:
  - python setup.py test
  - python -m coverage run --source=./mupit -m unittest discover
after_success:
  - coveralls
